name: credit
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy<1.24
  - pandas
  - matplotlib
  - cartopy
  - scikit-learn
  - pyarrow
  - pytest
  - xarray
  - netcdf4
  - pytorch
  - torchvision
  - wandb
  - pyyaml
  - cartopy
  - dask
  - distributed
  - dask-jobqueue
  - zarr
  - jupyter
  - pip:
    - einops
    - echo-opt
    - bridgescaler
    - rotary-embedding-torch
    - segmentation-models-pytorch
    - vector_quantize_pytorch
    - .

