name: credit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pyarrow
  - pytest
  - xarray
  - netcdf4
  - torch
  - pip:
    - bridgescaler
    - .

