name: credit
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - scikit-learn
  - pyarrow
  - pytest
  - xarray
  - netcdf4
  - pytorch
  - pip:
    - bridgescaler
    - rotary-embedding-torch
    - cartopy
    - .

