name: credit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - https://download.pytorch.org/whl/cpu/torch-2.5.1%2Bcpu-cp311-cp311-linux_x86_64.whl#sha256=07d7c9e069123d5af08b0cf0013d74f680b2d8be7d9e2cf561a52c90c55d9409
    - .
