name: credit
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - jupyter
  - numpy<1.24
  - pandas
  - pyarrow
  - pyyaml
  - distributed

## dev and ML ops
  - pytest
  - ruff
  - wandb

## Earth sciences and visualization
  - xarray
  - netcdf4
  - zarr
  - xesmf
  - geocat-comp
  - dask
  - dask-jobqueue
  - matplotlib
  - cartopy
  - ffmpeg

## ML
  - scikit-learn

  - pip:
    - mpi4py
    - einops
    - echo-opt
    - optuna==3.6.0
    - bridgescaler
    - torch 
    - torchvision 
    - rotary-embedding-torch
    - segmentation-models-pytorch>=0.3.4
    - vector_quantize_pytorch
    - torch-harmonics
    - torch_geometric
    - haversine
    - torchsummary
    - .

