save_loc: /glade/derecho/scratch/$USER/credit_example_model/
seed: 1000
data:
  source:
    ERA5:
      dataset_name: era5
      level_coord: '''level'''
      levels: [1.0, 9.0, 19.0, 29.0, 39.0, 49.0, 59.0, 69.0, 79.0, 89.0, 97.0, 104.0,
        111.0, 116.0, 122.0, 126.0, 131.0, 136.0]
      variables:
        prognostic:
          vars_3D: [u_component_of_wind, v_component_of_wind, temperature, specific_total_water]
          vars_2D: [SP, VAR_2T, VAR_10U, VAR_10V]
          path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/all_in_one/ERA5_mlevel_1deg_6h*
          filename_time_format: '%Y'
        dynamic_forcing:
          vars_2D: [toa_incident_solar_radiation]
          path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/all_in_one/ERA5_mlevel_1deg_6h*
          filename_time_format: '%Y'
        static:
          vars_2D: [z_norm, land_sea_mask]
          path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/static/ERA5_mlevel_1deg_static_subset.zarr
        diagnostic:
          vars_2D: [total_precipitation, evaporation, top_net_thermal_radiation, top_net_solar_radiation,
            surface_latent_heat_flux, surface_net_solar_radiation, surface_net_thermal_radiation,
            surface_sensible_heat_flux]
          path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/all_in_one/ERA5_mlevel_1deg_6h*
          filename_time_format: '%Y'
  timestep: 6h
  forecast_len: 1
  start_datetime: '2000-01-01'
  end_datetime: '2014-12-31'
  save_loc_physics: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/static/ERA5_mlevel_1deg_static_subset.zarr
  valid_forecast_len: 1
  backprop_on_timestep: [1, 2, 3, 5, 6, 7]
  retain_graph: false
model:
  type: wxformer
  frames: 1
  image_height: 181
  image_width: 360
  levels: 18
  channels: 4
  surface_channels: 4
  input_only_channels: 3
  output_only_channels: 8
  patch_width: 1
  patch_height: 1
  frame_patch_size: 1
  dim: [32, 64, 128, 256]
  depth: [2, 2, 2, 2]
  global_window_size: [8, 4, 2, 1]
  local_window_size: 4
  cross_embed_kernel_sizes:
  - [4, 8, 16, 32]
  - [2, 4]
  - [2, 4]
  - [2, 4]
  cross_embed_strides: [2, 2, 2, 2]
  attn_dropout: 0.0
  ff_dropout: 0.0
  upsample_with_ps: true
  use_spectral_norm: true
  upsample_v_conv: true
  decoder_attention_type: scse
  interp: false
  padding_conf:
    activate: true
    mode: earth
    pad_lat: [37, 38]
    pad_lon: [76, 76]
  post_conf:
    activate: true
    grid: equiangular
    tracer_fixer:
      activate: true
      denorm: true
      tracer_name: [specific_total_water, total_precipitation]
      tracer_thres: [1e-10, 0]
    global_mass_fixer:
      activate: false
      activate_outside_model: false
      simple_demo: false
      denorm: true
      grid_type: sigma
      midpoint: true
      fix_level_num: 7
      lon_lat_level_name: [lon2d, lat2d, coef_a, coef_b]
      surface_pressure_name: [SP]
      specific_total_water_name: [specific_total_water]
    global_water_fixer:
      activate: false
      activate_outside_model: false
      simple_demo: false
      denorm: true
      grid_type: sigma
      midpoint: true
      lon_lat_level_name: [lon2d, lat2d, coef_a, coef_b]
      surface_pressure_name: [SP]
      specific_total_water_name: [specific_total_water]
      precipitation_name: [total_precipitation]
      evaporation_name: [evaporation]
    global_energy_fixer:
      activate: false
      activate_outside_model: false
      simple_demo: false
      denorm: true
      grid_type: sigma
      midpoint: true
      lon_lat_level_name: [lon2d, lat2d, coef_a, coef_b]
      surface_pressure_name: [SP]
      air_temperature_name: [temperature]
      specific_total_water_name: [specific_total_water]
      u_wind_name: [u_component_of_wind]
      v_wind_name: [v_component_of_wind]
      surface_geopotential_name: [geopotential_at_surface]
      TOA_net_radiation_flux_name: [top_net_solar_radiation, top_net_thermal_radiation]
      surface_net_radiation_flux_name: [surface_net_solar_radiation, surface_net_thermal_radiation]
      surface_energy_flux_name: [surface_sensible_heat_flux, surface_latent_heat_flux]
    global_energy_fixer_updown:
      activate: false
      activate_outside_model: false
      simple_demo: false
      denorm: true
      grid_type: sigma
      midpoint: true
      lon_lat_level_name: [lon2d, lat2d, coef_a, coef_b]
      surface_pressure_name: [SP]
      surface_geopotential_name: [geopotential_at_surface]
      air_temperature_name: [temperature]
      specific_total_water_name: [specific_total_water]
      u_wind_name: [u_component_of_wind]
      v_wind_name: [v_component_of_wind]
      TOA_down_solar_name: [FSDS_TOA]
      TOA_up_solar_name: [FSUS_TOA]
      TOA_up_OLR_name: [FLUT_J]
      surf_down_solar_name: [FSDS_J]
      surf_up_solar_name: [FSUS]
      surf_down_LW_name: [FLDS_J]
      surf_up_LW_name: [FLUS]
      surf_SH_name: [SHFLX_J]
      surf_LH_name: [LHFLX_J]
loss:
  training_loss: mse
  validation_loss: mse
  use_power_loss: false
  use_spectral_loss: false
  spectral_lambda_reg: 0.1
  spectral_wavenum_init: 20
  latitude_weights: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/static/ERA5_mlevel_1deg_static_subset.zarr
  use_latitude_weights: false
  use_variable_weights: false
predict:
  mode: none
  batch_size: 1
  forecasts:
    type: custom
    start_year: 2019
    start_month: 1
    start_day: 1
    start_hours: [0, 12]
    duration: 1
    ic_interval_days: 1
    days: 2
  realtime:
    forecast_start_time: '2026-04-01 00:00:00'
    forecast_end_time: '2026-04-02 00:00:00'
    forecast_timestep: 6h
  initial_condition_path: /glade/derecho/scratch/$USER/gfs/
  variable_mapping: arcoera5
  model_level_file: ERA5_Lev_Info.nc
  save_vars: []
  metadata: era5.yaml
  save_forecast: /glade/derecho/scratch/$USER/example/
  use_laplace_filter: false
  climatology: /glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/ERA5_clim/ERA5_clim_1990_2019_6h_interp.nc
  interp_pressure:
    pressure_levels: [500.0, 850.0, 925.0]
    interp_fields: [u_component_of_wind, v_component_of_wind, temperature, specific_total_water]
    q_var: specific_total_water
    temperature_var: temperature
    surface_geopotential_var: geopotential_at_surface
  static_fields: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/static/ERA5_mlevel_1deg_static_subset.zarr
  ua_var_encoding:
    zlib: true
    complevel: 1
    shuffle: true
    chunksizes: [1, 18, 181, 360]
  pressure_var_encoding:
    zlib: true
    complevel: 1
    shuffle: true
    chunksizes: [1, 3, 181, 360]
  surface_var_encoding:
    zlib: true
    complevel: 1
    shuffle: true
    chunksizes: [1, 181, 360]
trainer:
  type: era5-gen1
  mode: none
  cpu_offload: false
  activation_checkpoint: false
  checkpoint_all_layers: false
  compile: false
  load_weights: false
  load_optimizer: false
  load_scaler: false
  load_scheduler: false
  save_backup_weights: true
  save_best_weights: true
  save_metric_vars: true
  update_learning_rate: false
  learning_rate: 0.001
  weight_decay: 0
  train_batch_size: 4
  valid_batch_size: 4
  ensemble_size: 1
  batches_per_epoch: 10
  valid_batches_per_epoch: 2
  stopping_patience: 50
  skip_validation: false
  epochs: 100
  start_epoch: 0
  num_epoch: 1
  reload_epoch: false
  use_scheduler: true
  scheduler:
    scheduler_type: cosine-annealing-restarts
    first_cycle_steps: 250
    cycle_mult: 6.0
    max_lr: 0.001
    min_lr: 1.0e-08
    warmup_steps: 249
    gamma: 0.7
  amp: false
  mixed_precision:
    param_dtype: float32
    reduce_dtype: float32
    buffer_dtype: float32
  grad_accum_every: 1
  grad_max_norm: dynamic
  thread_workers: 4
  valid_thread_workers: 1
  prefetch_factor: 2
  use_ema: false
  use_tensorboard: false
pbs:
  conda: credit-derecho
  project: NAML0001
  job_name: train_model
  walltime: '12:00:00'
  nodes: 1
  ncpus: 64
  ngpus: 4
  mem: 480GB
  queue: main
validation_data:
  start_datetime: '2014-01-01'
  end_datetime: '2018-12-31'
preblocks:
  norm:
    type: era5_normalizer
    args:
      mean_path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/mean_std/mean_6h_1979_2019_conserve_1deg.nc
      std_path: /glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_1deg/mean_std/std_residual_6h_1979_2019_conserve_1deg.nc
