# --------------------------------------------------------------------------------------------------------------------- #
# This yaml file implements hourly state-in-state-out crossformer
# on NSF NCAR HPCs (casper.ucar.edu and derecho.hpc.ucar.edu) 
# The model is trained on hourly model-level ERA5 data with top solar irradiance, geopotential, and land-sea mask
# Output variables: model level [U, V, T, Q], single level [SP, t2m], and 500 hPa [U, V, T, Z, Q]
# --------------------------------------------------------------------------------------------------------------------- #
save_loc: '/glade/work/$USER/CREDIT_runs/wxformer_1dg_cesm_data/'
seed: 1000

#net short top of model: FSNTOA
#net short bot of model: FSNS
#net long top of model: FLNT
#net long bot of model: FLNS
#note Q is vapor + condensed (total liquid)

data:
    # upper-air variables
    variables: ['U','V','T','Q']
    save_loc: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/f.e21.CREDIT_climate_*.zarr'
    
    # surface variables
    surface_variables: ['PS','PSL','TREFHT','SST']
    save_loc_surface: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/f.e21.CREDIT_climate_*.zarr'
    
    # dynamic forcing variables
    dynamic_forcing_variables: ['SOLIN']
    save_loc_dynamic_forcing: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/f.e21.CREDIT_climate_*.zarr'
    
    # static variables
    static_variables: ['z_norm','LANDM_COSLAT'] 
    save_loc_static: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/f.e21.CREDIT_climate.statics_1.0deg.nc'

    # diagnostic variables
    diagnostic_variables: ['PRECT','CLDTOT','TAUX','TAUY','U10', 'QFLX','FSNS','SHFLX','FLNS','FSNTOA','FLNT']
    save_loc_diagnostic: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/f.e21.CREDIT_climate_*.zarr'
     
    # mean / std path
    mean_path: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/mean_6h_1979_2010_32lev_1.0deg.nc'
    # regular z-score version
    # std_path: '/glade/derecho/scratch/ksha/CREDIT_data/std_1h_1979_2018_16lev_0.25deg.nc'
    # residual norm version
    std_path: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/std_6h_1979_2010_32lev_1.0deg.nc'
    
    # train / validation split
    train_years: [1979, 2009]
    valid_years: [2010, 2014]
    
    scaler_type: 'std_new'
    
    # state-in-state-out
    history_len: 1
    valid_history_len: 1
    
    # single step
    forecast_len: 0
    valid_forecast_len: 0
    
    one_shot: True
    lead_time_periods: 1
    skip_periods: null
    
    # compatible with the old 'std'
    static_first: True
    
trainer:
    type: standard # <---------- change to your type
    
    mode: none
    cpu_offload: False
    activation_checkpoint: True
    
    load_weights: False
    load_optimizer: False
    load_scaler: False
    load_sheduler: False
    num_epoch: 2
    
    skip_validation: False
    update_learning_rate: False
    
    save_backup_weights: True
    save_best_weights: True
    
    learning_rate: 1.0e-04 # <-- change to your lr
    weight_decay: 0
        
    train_batch_size: 10
    valid_batch_size: 5
        
    batches_per_epoch: 1000
    valid_batches_per_epoch: 4
    stopping_patience: 999
    
    start_epoch: 0
    num_epoch: 10
    reload_epoch: False
    epochs: &epochs 100
     
    use_scheduler: True
    scheduler: {'scheduler_type': 'cosine-annealing', 'T_max': *epochs,  'last_epoch': -1}
    
    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0
    
    # number of workers
    thread_workers: 4
    valid_thread_workers: 0
    
model:
    # crossformer example
    type: "crossformer"
    frames: 1                         # number of input states (default: 1)
    image_height: 192                 # number of latitude grids (default: 640)
    image_width: 288                 # number of longitude grids (default: 1280)
    levels: 32                       # number of upper-air variable levels (default: 15)
    channels: 4                       # upper-air variable channels
    surface_channels: 5               # surface variable channels
    input_only_channels: 3            # dynamic forcing, forcing, static channels
    output_only_channels: 2           # diagnostic variable channels
    
    patch_width: 1                    # number of latitude grids in each 3D patch (default: 1)
    patch_height: 1                   # number of longitude grids in each 3D patch (default: 1)
    frame_patch_size: 1               # number of input states in each 3D patch (default: 1)
    
    dim: [64, 128, 256, 512]           # Dimensionality of each layer
    depth: [2, 2, 8, 2]               # Depth of each layer
    global_window_size: [4, 4, 2, 1]   # Global window size for each layer
    local_window_size: 3             # Local window size
    cross_embed_kernel_sizes:         # kernel sizes for cross-embedding
    - [4, 8, 16, 32]
    - [2, 4]
    - [2, 4]
    - [2, 4]
    cross_embed_strides: [2, 2, 2, 2] # Strides for cross-embedding (default: [4, 2, 2, 2])
    attn_dropout: 0.                  # Dropout probability for attention layers (default: 0.0)
    ff_dropout: 0.                    # Dropout probability for feed-forward layers (default: 0.0)
    
    # map boundary padding
    pad_lon: 48             # number of grids to pad on 0 and 360 deg lon
    pad_lat: 48             # number of grids to pad on -90 and 90 deg lat
    
loss: 
    # the main training loss
    training_loss: "mse"
    
    # power loss (x), spectral_loss (x)
    use_power_loss: False
    use_spectral_loss: False
    
    # use latitude weighting
    use_latitude_weights: True
    latitude_weights: '/glade/derecho/scratch/dkimpara/LSM_static_variables_ERA5_zhght_onedeg.nc'
    
    # turn-off variable weighting
    use_variable_weights: False
    
predict:
    forecasts:
        type: "custom"       # keep it as "custom"
        start_year: 2010     # year of the first initialization (where rollout will start)
        start_month: 1       # month of the first initialization
        start_day: 1         # day of the first initialization
        start_hours: [0, 12] # hour-of-day for each initialization, 0 for 00Z, 12 for 12Z
        duration: 30         # number of days to initialize, starting from the (year, mon, day) above
                             # duration should be divisible by the number of GPUs 
                             # (e.g., duration: 384 for 365-day rollout using 32 GPUs)
        days: 2              # forecast lead time as days (1 means 24-hour forecast)
        
    save_forecast: '/glade/derecho/scratch/wchapman/CREDIT/cesm_wxformer/'
    save_vars: ['PS','QFLX','TREFHT','TAUX','TAUY','PRECT','CLDTOT']
    
    # turn-off low-pass filter
    use_laplace_filter: False
    
    # deprecated
    # save_format: "nc"

pbs: #derecho
    conda: "/glade/u/home/dkimpara/credit-derecho"
    project: "NAML0001"
    job_name: "wxformer_1h"
    walltime: "12:00:00"
    nodes: 2
    ncpus: 64
    ngpus: 4
    mem: '480GB'
    queue: 'main'
