save_loc: "/glade/derecho/scratch/schreck/repos/miles-credit/results/conus404"
seed: 222

data:
    variables: ['PSFC','Q500','Q850','T2','T500','T850','totalVap','U10','U1000','U250','U500','U850','V10','V1000','V250','V500','V850','Z050','Z1000','Z500','Z850']
    #variables: ['U850','V850','Q850']
    static_variables: []
    scaler_type: "std"
    save_loc: '/glade/derecho/scratch/mcginnis/???*'
    mean_path: '/glade/derecho/scratch/mcginnis/conus404/stats/all.avg.C404.nc'
    std_path: '/glade/derecho/scratch/mcginnis/conus404/stats/all.std.C404.nc'
    history_len: 2 
    forecast_len: 1
    valid_history_len: 2
    valid_forecast_len: 1
    time_step: 1

model:
    type: "unet"
    image_height: 512
    image_width: 512
    frames: 2
    architecture:
        name: "unet"
        encoder_name: "resnet34"
        encoder_weights: "imagenet"
    
trainer:
    mode: none # none, ddp, fsdp
    train_batch_size: 4
    valid_batch_size: 4
    batches_per_epoch: 1000 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 100
    learning_rate: 1.0e-04
    weight_decay: 1.0e-05
    start_epoch: 0
    epochs: 10
    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0
    thread_workers: 4
    valid_thread_workers: 0
    stopping_patience: 50
    teacher_forcing_ratio: 0.5 #0.9886539666794065
    stop_rollout: 0.9
    skip_validation: True
    load_weights: False
    load_optimizer: False
    use_scheduler: False
    update_learning_rate: True
    #scheduler: {'scheduler_type': 'cosine-annealing', first_cycle_steps: 500, cycle_mult: 6.0, max_lr: 5.0e-04, min_lr: 5.0e-07, warmup_steps: 499, gamma: 0.7}
    # scheduler: {scheduler_type: plateau, mode: min, factor: 0.1, patience: 5, cooldown: 2, min_lr: 1e-6, epsilon: 1e-8, verbose: true, threshold: 1e-4}
    scheduler: {'scheduler_type': 'lambda'}
     
loss: 
   training_loss: "mse"
   use_vgg: False
   use_spectral_loss: False
   spectral_wavenum_init: 15
   spectral_lambda_reg: 0.025791372491084097
   use_latitude_weights: False
   use_variable_weights: False
   latitude_weights: False

#pbs: #derecho
#    conda: "holodec"
#    project: "NAML0001"
#    job_name: "fuxi"
#    walltime: "24:00:00"
#    nodes: 8
#    ncpus: 64
#    ngpus: 4
#    mem: '480GB'
#    queue: 'preempt'
    
# pbs: # casper
#     conda: "/glade/work/schreck/miniconda3/envs/evidential"
#     job_name: 'latlon'
#     nodes: 1
#     ncpus: 8
#     ngpus: 1
#     mem: '128GB'
#     walltime: '12:00:00'
#     gpu_type: 'a100'
#     cpu_type: 'milan'
#     project: 'NAML0001'
#     queue: 'casper'
