# --------------------------------------------------------------------------------------------------------------------- #
# This yaml file implements 1 hourly state-in-state-out graph model
# on NSF NCAR HPCs (casper.ucar.edu and derecho.hpc.ucar.edu) 
# The model is trained on 1 hourly model-level ERA5 data with top solar irradiance, geopotential, and land-sea mask
# Output variables: model level [U, V, T, Q], single level [SP, t2m], and 500 hPa [U, V, T, Z, Q]
# --------------------------------------------------------------------------------------------------------------------- #
save_loc: '/glade/work/$USER/CREDIT_runs/graph_model/'
seed: 1000

data:
    # upper-air variables
    variables: ['U','V','T','Q']
    save_loc: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # surface variables
    surface_variables: ['SP','t2m','V500','U500','T500','Z500','Q500']
    save_loc_surface: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # dynamic forcing variables
    dynamic_forcing_variables: ['tsi']
    save_loc_dynamic_forcing: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # static variables
    static_variables: ['Z_GDS4_SFC','LSM'] 
    save_loc_static: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/static/ERA5_mlevel_cesm_static.zarr'
    
    # mean / std path
    mean_path: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/mean_6h_1979_2018_cesm.nc'
    # regular z-score version
    # std_path: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/std_6h_1979_2018_cesm.nc'
    # residual norm version
    std_path: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/std_residual_6h_1979_2018_cesm.nc'
    
    # train / validation split
    train_years: [1979, 2018]
    valid_years: [2018, 2019]
    
    # data workflow
    scaler_type: 'std_new'
    
    # state-in-state-out
    history_len: &history_len 1
    valid_history_len: *history_len
    
    forecast_len: 0
    valid_forecast_len: 0
    
    one_shot: True
    
    # 1 for hourly model
    lead_time_periods: 6
    
    # do not use skip_period
    skip_periods: null
    
    # compatible with the old 'std'
    static_first: True

    # backprop_on_timestep: [2]
    dataset_type: ERA5_MultiStep_Batcher # ERA5_and_Forcing_MultiStep MultiprocessingBatcherPrefetch ERA5_MultiStep_Batcher MultiprocessingBatcher
    
trainer:
    type: era5 # <---------- change to your type: single/multi-step training

    mode: ddp
    cpu_offload: False
    activation_checkpoint: False
    
    load_weights: False
    load_optimizer: False
    load_scaler: False
    load_scheduler: False

    skip_validation: False
    update_learning_rate: False

    save_backup_weights: True
    save_best_weights: True
    
    learning_rate: 0.250e-03 # <-- change to your lr
    weight_decay: 1.0e-06
    
    train_batch_size: 4
    valid_batch_size: 4
    
    batches_per_epoch: 0 # Total number of samples = 341,880  (1h) ~56,960 (6h)
    valid_batches_per_epoch: 100
    stopping_patience: 999
    
    start_epoch: 0
    num_epoch: 2
    reload_epoch: True
    epochs: &epochs 100
     
    use_scheduler: True
    scheduler: 
        scheduler_type: cosine-annealing
        T_max: 712300
    
    # Automatic Mixed Precision: False
    amp: False
    
    # rescale loss as loss = loss / grad_accum_every
    grad_accum_every: 1 
    # gradient clipping
    grad_max_norm: 2.0
    
    # number of workers
    thread_workers: 4
    valid_thread_workers: 4

    # compile 
    # compile: True
    prefetch_factor: 20
  
model:
    # crossformer example
    type: "graph"
    n_variables: 4
    n_surface_variables: 7
    n_static_forcing_variables: 3
    levels: 16
    history_len: *history_len
    down_hid_dims: [1024, 2048]
    down_dim_head: [128, 256]
    down_block_depth :  [6, 6]
    dropout: 0
    # down_hid_dims: [256, 512]
    # down_dim_head: [64, 128]
    # down_block_depth :  [2, 8]
    # dropout: 0
    down_graph_path : [
        "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_res_192_288_to_n80_k_3.nc",
        "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_r_2_n80.nc", # n80
        "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_n80_to_n48_k_3.nc",
        "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_r_2_n48.nc", # n48
        # "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_n48_to_n32_k_3.nc",
        # "/glade/derecho/scratch/dgagne/credit_scalers/grid_edge_pairs_r_2_n32.nc", # n32 
        ]
    use_spectral_norm: True
    use_coords: True
    use_checkpoint: False
    post_block: False
    
loss: 
    # the main training loss
    training_loss: "mse"
    
    # power loss (x), spectral_loss (x)
    use_power_loss: False
    use_spectral_loss: False
    
    # use latitude weighting
    use_latitude_weights: True
    latitude_weights: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/static/ERA5_mlevel_cesm_static.zarr'
    
    # turn-off variable weighting
    use_variable_weights: False
    
predict:
    mode: ddp
    forecasts:
        type: "custom"       # keep it as "custom"
        start_year: 2020     # year of the first initialization (where rollout will start)
        start_month: 1       # month of the first initialization
        start_day: 1         # day of the first initialization
        start_hours: [0, 12] # hour-of-day for each initialization, 0 for 00Z, 12 for 12Z
        duration: 8          # number of days to initialize, starting from the (year, mon, day) above
                             # duration should be divisible by the number of GPUs 
                             # (e.g., duration: 384 for 365-day rollout using 32 GPUs)
        days: 10             # forecast lead time as days (1 means 24-hour forecast)
        
    metadata: '/glade/u/home/akn7/miles-credit/credit/metadata/era5.yaml'
    save_forecast: '/glade/work/$USER/CREDIT_runs/graph_model/'
    # save_vars: ['SP','t2m','V500','U500','T500','Z500','Q500']
    
    batch_size: 8
    # turn-off low-pass filter
    use_laplace_filter: False
    
    # deprecated
    # save_format: "nc"

pbs: #derecho
    conda: "/glade/work/akn7/conda-envs/credit-derecho"
    project: "NAML0001"
    job_name: "graph_6h"
    walltime: "12:00:00"
    nodes: 8
    ncpus: 64
    ngpus: 4
    mem: '480GB'
    queue: 'main'
