# yaml file for the conus404 dataset

#---------------------
# CONUS404 data is (assumed to be) hourly data stored in daily netcdf
# files organized by year.  Each file contains 24 timesteps and all
# variables of the appropriate dimensionality.  Data has been
# compressed with lossy compression, and is chunked so that each file
# is a single chunk (i.e., 1 chunk = all space, 24 timesteps).
# 
# Naming convention: $path/YYYY/conus404.Nd.YYYY-MM-DD.nc
#
# data is normalized (using functions in transforms.py) in the
# dataloader in applications/train.py; no need for users to normalize
# them by hand.
#---------------------

# the location to save your workspace, it will have (1) pbs script,
# (2) a copy of this config, (3) model weights, (4) training_log.csv
# if save_loc does not exist, it will be created automatically

save_loc: /glade/work/$USER/CREDIT_runs/c404/
seed: 2222  # RNG seed


## To avoid errors / incompatibilities, declare options that are used
## repeatedly once, at the top level where they apply, and inherit
## them at the levels where they are used using the <<: pattern.  We
## could propagate configuration info downward in code, but inheriting
## it here dramatically simplifies things.

sampling: &samples
    history_len:  2 
    forecast_len: 1


# A downscaling model is trained on two datasets, one for the
# high-resolution output from the model being emulated, and one for
# the low-resolution driving data (boundary conditions coming from a
# reanalysis or GCM).  All data needs to have the same dimensions in X
# & Y, so we interpolate the low-res data onto a coarsened version of
# the high-res grid, then apply the 'expand' and 'pad' transforms to
# stretch it out to match the actual high-res grid.  This saves us
# from needing to store a high-res of the driver data that would be
# 25x bigger and blow up our scratch quota.  (We don't need to worry
# about the Z dimension because it gets concatenated along the
# 'variable' dimension; i.e., different levels of a 3D variable are
# treated as different variables.)

# 'boundary' variables are input-only, used in both training and
#  inference

# 'diagnostic' variables are output-only

# 'prognostic' variables are input-output; the value predicted as an
#  output for time T is recycled as an input for predicting time T+1 in
#  inference

# 'unused' variables don't actually need to be listed in the yaml
# file, they're just here for reference and convenience when changing
#  around the model configuration

# listing variables in the order they appear in the netcdf file should
# result in faster reads from disk.  By default, NCO commands that
# rewrite their outputs alphabetize variables.


# The 'data', 'dataset', and 'transforms' sections below are used to
# initialize DownscalingDataset, DataMap, and DataTransform objects,
# respectively.  You pass **config['data'] (etc.) to the constructor,
# so the options here correspond to constructor arguments.

data_defaults: &ddefault
    <<: *samples

    # file globs are defined relative to the top-level data rootpath
    rootpath: /glade/derecho/scratch/mcginnis/credit

    first_date:   "1980-01-01"
    last_date:    "1984-12-31"

    # note: first_date and last_date must be quoted so that they
    # remain strings; otherwise the yaml parser converts them to
    # datetime objects, which can't handle non-standard GCM calendars.



data:
    <<: *ddefault

    datasets:
        ## hires component:
        ## CONUS404 data on native 4km grid; hourly, 1979-10 to 2022-09

        ## static WRF fields extracted from 'wrfconstants_usgs404.nc'
        conus404_static:
            <<: *ddefault
            glob: 'conus404/conus404.static.nc'
            dim: static
            normalize: True   # scale min,max == [0,1] iff dim = static
            variables:
                boundary:
                    - HGT       # terrain height / orography
                    - LANDMASK  # land/sea mask (0=water, 1=land)
                unused:
                    - COSALPHA  # local cosine of map rotation
                    - E         # coriolis cosine latitude term
                    - F         # coriolis sine latitude term
                    - SINALPHA  # local sine of map rotation
                    - VAR       # orographic variance
                    - VAR_SSO   # variance of subgrid-scale orography
                    - XLAT      # latitude
                    - XLONG     # longitude
            transforms:
                default: none   # scaled during load; nothing further needed


        ## NOTE that U and V are on staggered grids that are 1 larger in
        ## the x- and y- dimensions (respectively) than the other
        ## variables; they have been trimmed by 1 on the western and
        ## southern edges (respectively) to match the dimensionality of
        ## the non-staggered grids.

        conus404_3D:
            <<: *ddefault
            glob: 'conus404/3d/*/conus404.3d.*.nc'
            dim: 3D
            variables:
                prognostic:
                    - TK      # air temperature
                    - U       # U-component of wind *with respect to model grid*
                    - V       # V-component of wind *with respect to model grid*
                diagnostic:
                    - Z       # geopotential height
                unused:
                    - P       # total pressure (dataset uses hybrid sigma coordinates)
                    - QVAPOR  # water vapor mixing ratio                    
            transforms:
                paramfiles:
                    mmin: 'norms/min.conus404_3d.nc'
                    mmax: 'norms/max.conus404_3d.nc'
                default:
                    minmax: paramfile


        conus404_2D:
            <<: *ddefault
            glob: 'conus404/2d/*/conus404.2d.*.nc'
            dim: 2D
            variables:
                boundary:
                    - COSZEN  # cosine of solar zenith angle
                prognostic:
                    - T2      # 2-meter air temperature
                    - U10     # u-wind at 10 meters
                    - V10     # v-wind at 10 meters
                diagnostic:
                    - PSFC    # surface pressure
                unused:
                    - PREC_ACC_NC # total precip (mm) over previous (1-hr) timestep
                    - Q2      # water vapor mixing ratio at 2 meters
                    - SWDNB   # shortwave downwelling at bottom (instantaneous)
                    - SNOW    # snow water equivalent
                    - TD2     # 2-meter dewpoint temperature
                    - totalVap # column-integrated water vapor content
            transforms:
                paramfiles:
                    mmin: 'norms/min.conus404_2d.nc'
                    mmax: 'norms/max.conus404_2d.nc'
                default:
                    minmax: paramfile
                PREC_ACC_NC:
                    clip:
                        cmin: 0
                    minmax: paramfile
                    power:
                        exponent: 0.25



        ## lores component:
        ## driving ERA5 & TOA solar data on coarsened version of CONUS404 grid

        ## insolation data calculated using miles-credit applications
        ## script calc_global_solar.py, regridded to coarsened
        ## CONUS404 grid; hourly, 1979-2024

        solar:
            <<: *ddefault
            glob: 'solar/tisr.20km.*.nc'
            dim: 2D
            variables:
                boundary:
                    - tisr      # TOA incident solar radiation (J/m^2, integral dt)
            transforms:
                paramfiles:
                    mmin: 'norms/min.solar.nc'
                    mmax: 'norms/max.solar.nc'
                tisr:
                    minmax: paramfile
                    expand:
                        by: 5
                    pad:
                        left: 1
                        right: 1


          ## ERA5 data regridded to coarsened CONUS404 grid.  Source
          ## data is interpolated to pressure levels and global 0.25
          ## degree grid.  (Variables are in alphabetical order except
          ## for R, which is last.)  hourly, 1979-2023

        era5_3D:
            <<: *ddefault
            glob: 'era5/3d/*/era5.3d.*.nc'
            dim: 3D
            zstride: 6
            variables:
                boundary:
                    - T   # temperature
                    - Z   # geopotential
                unused:
                    - U   # u-winds
                    - V   # v-winds
                    - R   # humidity
            transforms:
                paramfiles:
                    mmin: 'norms/min.era5_3d.nc'
                    mmax: 'norms/max.era5_3d.nc'
                default:
                    minmax: paramfile
                    expand:
                        by: 5
                    pad:
                        left: 1
                        right: 1

        era5_2D:
            <<: *ddefault
            glob: 'era5/2d/*/era5.2d.*.nc'
            dim: 2D
            variables:
                boundary:
                    - MSL      # mean sea-level pressure
                    - VAR_2T   # 2-meter temperature
                unused:
                    - SP       # surface pressure
                    - TCWV     # total column water vapor
                    - VAR_10U  # 10-meter u-wind
                    - VAR_10V  # 10-meter v-wind
            transforms:
                paramfiles:
                    mmin: 'norms/min.era5_2d.nc'
                    mmax: 'norms/max.era5_2d.nc'
                default:
                    minmax: paramfile
                    expand:
                        by: 5
                    pad:
                        left: 1
                        right: 1


model:
    type: "crossformer_downscaling"
    image_height: 1015
    image_width: 1367
    frames: 2
#    architecture:  # none, just use defaults


trainer:
    type: "conus404"
    mode: none # none, ddp, fsdp
    train_batch_size: 4
    valid_batch_size: 4
    batches_per_epoch: 10 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 100
    learning_rate: 1.0e-04
    weight_decay: 1.0e-05
    start_epoch: 0
    epochs: 4  # 30 years hourly = 262,980; 66 x 1000-batch epoch =~ 1 full pass
    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0
    thread_workers: 4
    valid_thread_workers: 0
    stopping_patience: 50
    teacher_forcing_ratio: 0.5 #0.9886539666794065
    stop_rollout: 0.9
    skip_validation: True
    load_weights: False
    load_optimizer: False
    use_scheduler: False
    update_learning_rate: True
    #scheduler: {'scheduler_type': 'cosine-annealing', first_cycle_steps: 500, cycle_mult: 6.0, max_lr: 5.0e-04, min_lr: 5.0e-07, warmup_steps: 499, gamma: 0.7}
    # scheduler: {scheduler_type: plateau, mode: min, factor: 0.1, patience: 5, cooldown: 2, min_lr: 1e-6, epsilon: 1e-8, verbose: true, threshold: 1e-4}
    scheduler: {'scheduler_type': 'lambda'}

loss:
   training_loss: "mse"
   use_vgg: False
   use_spectral_loss: False
   spectral_wavenum_init: 15
   spectral_lambda_reg: 0.025791372491084097
   use_latitude_weights: False
   use_variable_weights: False
   latitude_weights: False


predict:
    start: "2017-11-01"
    finish: "2017-11-10"
#    finish: "2022-09-30"
    autoregressive: False
    use_laplace_filter: False
    save_format: "nc"


#visualization:
#    surface_visualize:
#        variable_keys: ['U10','U1000','U250','U500','U850','V10','V1000','V250','V500','V850']
#        variable_names: ['U10','U1000','U250','U500','U850','V10','V1000','V250','V500','V850']
#        file_name_prefix: "unet-03-wind"
#    save_options: {'dpi': 250,
#                   'format':'png'}
#    video_format: 'none'


pbs: # casper
    conda: "credit"
    job_name: 'down-simple-test'
    nodes: 1
    ncpus: 8
    ngpus: 1
    mem: '128GB'
    walltime: '4:00:00'
#    walltime: '24:00:00'
    gpu_type: 'a100'
    project: 'NRIS0001'
    queue: 'casper'
