# Example of a multi-source data configuration. Does not contain any model config options.
data:
    start_datetime: "2021-06-01"
    end_datetime: "2021-06-04"
    timestep: "6h"
    forecast_len: 1
    source:
        ERA5_LowerAir:
            dataset_type: "local"
            level_coord: "level"
            levels: [95, 100, 105, 110, 120, 130, 136, 137]
            variables:
                prognostic:
                    vars_3D: ['U','V','T','Q']
                    vars_2D: ['SP','t2m', 'V500','U500','T500','Z500','Q500']
                    path: '/glade/derecho/scratch/cbecker/test_CREDIT_data/era5_local_testing_data_onedeg_2021.nc'
                    filename_time_format: "%Y"

                diagnostic: null

                dynamic_forcing: null

                static:
#                    vars_2D: ['Z_GDS4_SFC','LSM']
                    vars_2D: ['LSM']
                    path: '/glade/derecho/scratch/cbecker/test_CREDIT_data/LSM_static_variables_ERA5_zhght_ONEDEG.nc'
                    # single file — filename_time_format not needed
        
        ERA5_UpperAir:
            dataset_type: "local"
            level_coord: "level"
            levels: [10, 30, 40, 50, 60, 70, 80, 90]
            variables:
                prognostic:
                    vars_3D: ['U','V','T','Q']
                    path: '/glade/derecho/scratch/cbecker/test_CREDIT_data/era5_local_testing_data_onedeg_2021.nc'
                    filename_time_format: "%Y"
                
                diagnostic: null

                dynamic_forcing:
                    vars_2D: ['tsi']
                    path: '/glade/derecho/scratch/cbecker/test_CREDIT_data/era5_local_testing_data_onedeg_2021.nc'
                    filename_time_format: "%Y"

                static: null

preblocks:
    log_transform:
      type: "log_transform"
      args:
          variables:
                - 'ERA5_LowerAir/prognostic/3d/U'
                - 'ERA5_LowerAir/prognostic/3d/V'
                - 'ERA5_LowerAir/prognostic/3d/T'
                - 'ERA5_LowerAir/prognostic/3d/Q'
                - 'ERA5_LowerAir/prognostic/2d/SP'
                - 'ERA5_LowerAir/prognostic/2d/t2m'
                - 'ERA5_LowerAir/dynamic_forcing/2d/tsi'
                - 'ERA5_LowerAir/static/2d/LSM'
          data_types:
            - 'input'
            - 'target'
    concatenate:
      type: "concat"

postblocks:
  reconstruct:
    type: "reconstruct"